name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test and publish coverage
      run: export COVERALLS_REPO_TOKEN=$(cat .coveralls | base64 -d | xargs) && ./gradlew jacocoTestReport coverallsJacoco
