name: check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: export COVERALLS_REPO_TOKEN=$(cat .coveralls | base64 -d | xargs)
    - name: test and publish coverage
      run: ./gradlew jacocoTestReport coverallsJacoco
